"""Load added

Revision ID: f333f2e6ce93
Revises: 7f28c0a20551
Create Date: 2026-02-21 08:36:45.549314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f333f2e6ce93'
down_revision: Union[str, Sequence[str], None] = '7f28c0a20551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loans_book_uid'), table_name='loans')
    op.drop_index(op.f('ix_loans_borrowed_at'), table_name='loans')
    op.drop_index(op.f('ix_loans_member_uid'), table_name='loans')
    op.drop_index(op.f('ix_loans_uid'), table_name='loans')
    op.drop_table('loans')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('book_uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('member_uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('borrowed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('reissued_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('returned_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_uid'], ['books.uid'], name=op.f('loans_book_uid_fkey')),
    sa.ForeignKeyConstraint(['member_uid'], ['members.uid'], name=op.f('loans_member_uid_fkey')),
    sa.PrimaryKeyConstraint('uid', name=op.f('loans_pkey')),
    sa.UniqueConstraint('book_uid', 'member_uid', name=op.f('uq_loans_book_member'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_loans_uid'), 'loans', ['uid'], unique=True)
    op.create_index(op.f('ix_loans_member_uid'), 'loans', ['member_uid'], unique=False)
    op.create_index(op.f('ix_loans_borrowed_at'), 'loans', ['borrowed_at'], unique=False)
    op.create_index(op.f('ix_loans_book_uid'), 'loans', ['book_uid'], unique=False)
    # ### end Alembic commands ###
